#!/usr/bin/env ruby

git_bundles = [ 
  'git://github.com/airblade/vim-gitgutter.git',
  'git://github.com/arafatm/todohabit.vim.git',
  'git://github.com/mattn/gist-vim.git',
  'git://github.com/msanders/snipmate.vim.git',
  'git://github.com/scottmcginness/vim-jquery.git',
  'git://github.com/thinca/vim-ft-markdown_fold.git',
  'git://github.com/tpope/vim-fugitive.git',
  'git://github.com/tpope/vim-rails.git',
  'git://github.com/tpope/vim-bundler.git',
  'git://github.com/vim-ruby/vim-ruby.git',
  'git://github.com/vim-scripts/JavaScript-Indent.git',
  'git://github.com/vim-scripts/Markdown.git',
  'git://github.com/rodjek/vim-puppet.git'
]

vim_org_scripts = [
  ["IndexedSearch", "7062",  "plugin"],
  ["jquery",        "12107", "syntax"],
]

require 'fileutils'
require 'open-uri'

`mkdir autoload`
`mkdir bundle`

`curl -Sso ~/.vim/autoload/pathogen.vim https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim`

bundles_dir = File.join(File.dirname(__FILE__), "bundle")

FileUtils.cd(bundles_dir)

puts "trashing everything (lookout!)"
Dir["*"].each {|d| FileUtils.rm_rf d }

git_bundles.each do |url|
  dir = url.split('/').last.sub(/\.git$/, '')
  puts "unpacking #{url} into #{dir}"
  `git clone #{url} #{dir}`
  FileUtils.rm_rf(File.join(dir, ".git"))
end

vim_org_scripts.each do |name, script_id, script_type|
  puts "downloading #{name}"
  local_file = File.join(name, script_type, "#{name}.vim")
  FileUtils.mkdir_p(File.dirname(local_file))
  File.open(local_file, "w") do |file|
    file << open("http://www.vim.org/scripts/download_script.php?src_id=#{script_id}").read
  end
end
