#! /usr/bin/bash

alias g='git'
alias gac='git add .; git commit -a -m'
alias gnote='git commit --allow-empty -m'
alias gal='alias |grep git'
alias gbr='git branch'
alias gca='git commit -a -m'
alias gci='git commit'
alias gco='git checkout'
alias gdf='git diff'
alias glg='git log --oneline --decorate'
alias glol='git log --graph --decorate --pretty=oneline --abbrev-commit'
alias glola='git log --graph --decorate --pretty=oneline --abbrev-commit --all'
alias gls='git ls-files'
alias gst='git status'
alias commit='git push; git push heroku master'

